package Tracker.Mensuration.Entity;

import lombok.Data;
import org.springframework.stereotype.Component;

@Component
@Data
public class Tips {
    String[] tips = {
            "Track your menstrual cycle using an app or calendar.",
            "Drink plenty of water to stay hydrated and reduce bloating.",
            "Choose the right menstrual product (pads, tampons, menstrual cups, period underwear).",
            "Change your sanitary products every 4-6 hours to maintain hygiene.",
            "Wash your hands before and after changing your menstrual products.",
            "Use a warm compress or heating pad to ease cramps.",
            "Eat iron-rich foods like spinach to replenish lost iron during menstruation.",
            "Gentle exercise, like walking or yoga, can help relieve cramps.",
            "Get plenty of rest to combat fatigue during your period.",
            "Avoid scented menstrual products to prevent irritation.",
            "Wear breathable cotton underwear to prevent infections.",
            "Manage stress through relaxation techniques like deep breathing or meditation.",
            "If your periods are irregular, heavy, or painful, consult a doctor.",
            "Use pain relievers like ibuprofen as needed to ease menstrual pain.",
            "Educate yourself about menstruation and related health matters.",
            "Wrap used pads or tampons in tissue before disposing of them.",
            "Keep a menstrual kit with pads, pain relievers, and spare underwear.",
            "Discuss menstruation openly with trusted friends or family.",
            "Avoid excessive caffeine and salty foods to reduce bloating and cramps.",
            "Carry wet wipes when traveling to maintain hygiene during your period.",
            "Always store menstrual products in a cool, dry place to avoid contamination.",
            "If using a menstrual cup, ensure it's cleaned and sterilized properly between uses.",
            "Avoid wearing tight clothing during your period to avoid irritation.",
            "Change tampons or menstrual cups every 4-8 hours to prevent toxic shock syndrome (TSS).",
            "Consider a period tracker to help manage your cycle and symptoms.",
            "Keep your bathroom well-stocked with menstrual products in case of unexpected periods.",
            "Use unscented toilet paper and wipes to avoid irritation around the vaginal area.",
            "When using pads, make sure they're the right size for your flow to avoid leakage.",
            "Don’t skip meals or stay hungry during your period to keep energy levels stable.",
            "Use a menstrual cup for a more eco-friendly alternative to tampons and pads.",
            "Try herbal teas like ginger or chamomile to soothe cramps.",
            "Wear loose clothing to feel more comfortable during your period.",
            "If you’re using a tampon, ensure it's the right absorbency for your flow to prevent discomfort.",
            "If you have a heavy flow, consider using a menstrual cup or super absorbent pads.",
            "Use menstrual underwear for extra protection during your period.",
            "Rest and take it easy during the first days of your period if you're feeling fatigued.",
            "Consider using natural remedies like heat or acupuncture for pain relief.",
            "Avoid soaking in hot tubs or swimming in public pools while on your period.",
            "Make sure to sleep with a towel or period-protection to avoid staining your sheets.",
            "Wear dark clothing during the heaviest days of your period for added peace of mind.",
            "Track any unusual symptoms like heavy bleeding or irregular cycles and consult a doctor.",
            "Practice pelvic exercises like Kegels to improve menstrual health.",
            "Make sure to use a menstrual product that feels comfortable for your body.",
            "Choose a menstrual product that is made of organic, chemical-free materials to reduce irritation.",
            "Consider using a menstrual diary to track symptoms and changes over time.",
            "Always carry extra pads or tampons in your bag to avoid emergencies.",
            "Wash your menstrual products regularly to maintain cleanliness and hygiene.",
            "Take a hot shower to help relax your muscles and relieve cramps.",
            "Avoid tight or restrictive clothing to improve comfort during your period.",
            "Use a night-time sanitary pad for overnight protection to avoid leakage.",
            "Try an exercise routine to alleviate cramps and improve circulation.",
            "Avoid excessive sugar and fatty foods to reduce bloating and discomfort.",
            "Use cold packs on your abdomen or back to alleviate period pain.",
            "Use menstrual products made from eco-friendly materials to reduce waste.",
            "Be mindful of your emotional health, as hormonal changes can affect mood.",
            "Sleep with your legs elevated to relieve bloating and discomfort.",
            "Stay active during your period, as light physical activity can improve circulation.",
            "Make sure to dispose of used products responsibly, wrapping them up properly.",
            "Avoid wearing synthetic fabrics, as they can cause irritation during menstruation.",
            "Stay hydrated with herbal teas or lemon water for a soothing effect.",
            "Do not rush to stop your period with over-the-counter pills without consulting a doctor.",
            "Try deep breathing exercises to reduce stress and tension during menstruation.",
            "Avoid using strong chemical products on your intimate areas to prevent irritation.",
            "Don’t use feminine sprays or douches, as they can disrupt the natural balance.",
            "If you use a tampon, always ensure it’s fully inserted to avoid leakage.",
            "Keep your intimate area dry to prevent infections like yeast infections.",
            "Consider using a menstrual disc for a different, less bulky option to a tampon.",
            "Use period-proof panties if you want to avoid using traditional menstrual products.",
            "When traveling, make sure to bring a travel-size bottle of menstrual products.",
            "Eat small meals throughout the day to keep energy levels stable during menstruation.",
            "Make sure to use a sanitary product that matches your personal comfort level.",
            "Consider switching to organic cotton menstrual products if you have sensitive skin.",
            "Take short breaks during long periods of sitting to avoid discomfort during your period.",
            "Be patient with your body and understand that periods can affect each person differently.",
            "In case of excessive bleeding, consult a doctor to rule out medical conditions.",
            "Talk to your doctor about different birth control methods if your periods are too painful.",
            "Keep track of your period symptoms to help manage future cycles.",
            "Don’t forget to take care of your mental health during your period.",
            "Take care of your body by practicing self-care during your period.",
            "Consider trying meditation to help cope with stress and menstrual cramps.",
            "Avoid alcohol and tobacco, as they can exacerbate cramps and other symptoms.",
            "Consider switching to reusable menstrual products to save money and reduce waste.",
            "Use gentle products on your skin during your period to avoid irritation.",
            "If you're feeling bloated, reduce salty foods and drink more water.",
            "Consider wearing a menstrual cup if you want a longer-lasting, eco-friendly solution.",
            "Make sure to stay hydrated with non-caffeinated beverages during menstruation.",
            "Try taking a warm bath to soothe muscle aches during your period.",
            "Don’t ignore unusual symptoms, like prolonged bleeding or severe pain.",
            "Consult a doctor about your options if you have difficulty managing heavy flow.",
            "Keep a good balance of rest and activity during your menstrual cycle.",
            "Be kind to yourself and take it easy during the challenging days of your period.",
            "Include omega-3 rich foods like salmon or chia seeds in your diet to help reduce inflammation.",
            "Use apps to set reminders for changing your menstrual product regularly.",
            "Stay away from harsh soaps and cleansers for intimate areas to maintain the natural pH balance.",
            "Practice good posture to reduce back pain during your period.",
            "Opt for non-restrictive sleepwear for better comfort during your period.",
            "Limit your intake of carbonated drinks to avoid bloating.",
            "Use lavender oil in a diffuser for relaxation during stressful period days.",
            "Make sure to shower regularly during your period to stay fresh and clean.",
            "Apply aloe vera gel for soothing skin irritation caused by menstrual pads.",
            "Experiment with acupressure points for natural cramp relief.",
            "Wear leak-proof period shorts or leggings for added security during heavy flow days.",
            "Try aromatherapy with peppermint or eucalyptus oil for energy and mood improvement.",
            "Pack a small zip-lock pouch to discreetly carry used menstrual products until disposal.",
            "Listen to soothing music or white noise to help ease period-related insomnia.",
            "Keep an emergency stash of menstrual products in your car or office.",
            "Use breathable liners or panty shields for light spotting or pre-period discharge.",
            "Try drinking turmeric milk for its anti-inflammatory benefits during menstruation.",
            "Carry a small deodorizer or scented sachet in your bag for freshness.",
            "Make homemade heating packs with rice and a sock for reusable cramp relief.",
            "Wear comfortable flat shoes to reduce period-related leg pain or swelling.",
            "Consider a probiotic supplement to maintain healthy gut bacteria during your cycle.",
            "Plan relaxing activities like reading or drawing to keep your mind off discomfort.",
            "Avoid skipping workouts entirely—try gentle stretches instead to ease tension.",
            "Drink coconut water for natural electrolytes and hydration during your period.",
            "Be patient with period-related mood swings—they are temporary and manageable.",
            "Keep a journal to track food, exercise, and symptoms to identify helpful patterns.",
            "Try magnesium-rich foods like nuts or seeds to reduce cramps and headaches.",
            "Use reusable cloth pads if you prefer an eco-friendly and cost-effective option.",
            "Wash reusable menstrual products with fragrance-free, gentle detergents.",
            "Avoid waxing or shaving around your period, as skin tends to be more sensitive.",
            "Sleep on your side with a pillow between your legs to relieve lower back pain.",
            "Use a menstrual cup with measuring lines to track flow and monitor for abnormalities.",
            "Wear loose and soft scarves or layers to combat period-related chills or discomfort.",
            "Drink hibiscus or raspberry leaf tea to support menstrual health naturally.",
            "Keep a small notepad or app handy to note questions or concerns for your gynecologist.",
            "Eat bananas or avocados to boost potassium and relieve bloating and cramps.",
            "Schedule your most relaxing activities on the first day of your period.",
            "Consider plant-based pain relievers like ginger capsules for period pain.",
            "Stay informed about menstrual myths and educate younger generations.",
            "Use body lotions or oils to massage your abdomen, promoting relaxation and pain relief.",
            "Include foods high in vitamin B6, like chicken or sunflower seeds, to stabilize mood.",
            "Experiment with aromatherapy rollers for discreet, on-the-go stress relief.",
            "Build a supportive community by sharing period tips and experiences with friends.",
            "Avoid heavy lifting or high-impact sports during days with severe cramping.",
            "Learn how your cycle affects your emotions and plan accordingly.",
            "Switch to nighttime-specific menstrual products for long-lasting overnight protection.",
            "Use a menstrual cup or disc for swimming without interruptions during your period.",
            "Prioritize iron supplements if recommended by your doctor for heavy bleeding."
            // You can continue adding tips to complete the array up to 365.
    };


    String[] tipsInNepali = {
            "तपाईंको महिनावारी चक्र ट्र्याक गर्नको लागि एप वा क्यालेन्डर प्रयोग गर्नुहोस्।",
            "पानी धेरै पिउनुहोस् ताकि शरीरलाई हाइड्रेट राख्न र फुलावट कम गर्न मद्दत होस्।",
            "सही महिनावारी उत्पादन (प्याड, ट्याम्पन, महिनावारी कप, अवधि अन्डरवेयर) छान्नुहोस्।",
            "स्यानिटरी उत्पादनहरू ४-६ घण्टा भित्र परिवर्तन गर्नुहोस् ताकि सरसफाइ कायम राख्न सकियोस्।",
            "महिनावारी उत्पादनहरू परिवर्तन गर्नु अघि र पछि हात धुनुहोस्।",
            "क्र्याम्प कम गर्न तातो कम्प्रेस वा हीटिंग प्याड प्रयोग गर्नुहोस्।",
            "पालुंगो जस्ता फलाम युक्त खाना खाएर मासिक धर्मको समयमा हराएको फलाम पुनःस्थापना गर्नुहोस्।",
            "हल्का व्यायाम, जस्तै हिँड्ने वा योगाले क्र्याम्प कम गर्न मद्दत गर्दछ।",
            "थकान हटाउन पर्याप्त आराम गर्नुहोस्।",
            "सुगन्धित महिनावारी उत्पादनहरू प्रयोग नगर्नुहोस् ताकि जलनबाट बच्न सकियोस्।",
            "सांस लिन मिल्ने कपासका अन्तर्वस्त्र लगाउनुहोस् ताकि संक्रमणबाट बच्न सकियोस्।",
            "तनाव व्यवस्थापन गर्न गहिरो सास लिने वा ध्यान जस्ता रिल्याक्सेसन प्रविधि अपनाउनुहोस्।",
            "यदि तपाईंको महिनावारी अनियमित, धेरै गहिरो, वा दुखाइपूर्ण छ भने डाक्टरसँग परामर्श गर्नुहोस्।",
            "महिनावारी दुखाइ कम गर्न आवश्यक परेमा इबुप्रोफेन जस्ता पेन रिलिभरहरू प्रयोग गर्नुहोस्।",
            "महिनावारी र स्वास्थ्यसँग सम्बन्धित जानकारी सिक्नुहोस्।",
            "प्रयोग गरिएका प्याड वा ट्याम्पनलाई टिस्युमा बेरेर फाल्नुहोस्।",
            "प्याड, पेन रिलिभर, र अतिरिक्त अन्तर्वस्त्र सहितको महिनावारी किट राख्नुहोस्।",
            "विश्वासिला साथी वा परिवारसँग महिनावारीका बारेमा खुला कुरा गर्नुहोस्।",
            "अत्यधिक क्याफिन र नुनिलो खाना खपत नगर्नुहोस् ताकि फुलावट र क्र्याम्प कम होस्।",
            "यात्रा गर्दा सरसफाइ कायम राख्न भिजेका वाइपहरू बोकेर हिँड्नुहोस्।",
            "महिनावारी उत्पादनहरू चिसो र सुक्खा ठाउँमा राख्नुहोस् ताकि दूषित हुन नपाओस्।",
            "यदि महिनावारी कप प्रयोग गर्दै हुनुहुन्छ भने प्रत्येक प्रयोग बीचमा सफा र स्टेरिलाइज गर्नुहोस्।",
            "महिनावारीको समयमा तंग कपडा लगाउनबाट बच्नुहोस् ताकि असुविधा नहोस्।",
            "ट्याम्पन वा महिनावारी कप ४-८ घण्टामा परिवर्तन गर्नुहोस् ताकि टक्सिक शक सिन्ड्रोम (TSS) बाट बच्न सकियोस्।",
            "महिनावारी ट्र्याकर प्रयोग गर्नुहोस् ताकि चक्र र लक्षणहरू व्यवस्थापन गर्न सकियोस्।",
            "अप्रत्याशित महिनावारीका लागि बाथरूममा पर्याप्त उत्पादनहरू राख्नुहोस्।",
            "अन्तरंग क्षेत्रमा जलनबाट बच्न बिना सुगन्धयुक्त टिस्यु वा वाइप प्रयोग गर्नुहोस्।",
            "प्याड प्रयोग गर्दा लिकेज रोक्नको लागि फ्लो अनुसार सही आकारको प्याड प्रयोग गर्नुहोस्।",
            "महिनावारीको समयमा उर्जा स्तर स्थिर राख्न खाना छोड्नु वा भोकै बस्न नगर्नुहोस्।",
            "एक अधिक वातावरणमैत्री विकल्पको लागि महिनावारी कपको प्रयोग गर्न विचार गर्नुहोस्।",
            "अदरक वा क्यामोमाइल जस्ता जडिबुटी चिया क्र्याम्प कम गर्नको लागि प्रयास गर्नुहोस्।",
            "आरामदायी महसुस गर्न खुकुलो कपडा लगाउनुहोस्।",
            "यदि तपाईं ट्याम्पन प्रयोग गर्दै हुनुहुन्छ भने फ्लो अनुसारको सोख्ने क्षमता भएको ट्याम्पन छान्नुहोस्।",
            "यदि तपाईंको फ्लो भारी छ भने महिनावारी कप वा सुपर सोख्ने प्याड प्रयोग गर्नुहोस्।",
            "अवधि अन्डरवेयर प्रयोग गर्नुहोस् यदि तपाईंलाई थप सुरक्षाको आवश्यकता छ।",
            "थकित महसुस भएको खण्डमा महिनावारीको पहिलो दिन आराम गर्नुहोस्।",
            "पीडाको प्राकृतिक उपचारको लागि तातो वा एक्युपंक्चर प्रयास गर्नुहोस्।",
            "महिनावारीको समयमा तातो पानीको पोखरी वा सार्वजनिक पोखरीमा डुबुल्की नमार्न प्रयास गर्नुहोस्।",
            "तपाईंको ओछ्यानको पाना दागबाट बच्नका लागि तौलिया वा अवधि-सुरक्षा उत्पादनको साथ सुत्नुहोस्।",
            "महिनावारीको सबैभन्दा गहिरो दिनहरूमा अँध्यारो कपडा लगाउनुहोस्।",
            "गहिरो रक्तस्राव वा अनियमित चक्र जस्ता असामान्य लक्षणहरू ट्र्याक गर्नुहोस् र डाक्टरसँग परामर्श गर्नुहोस्।",
            "श्रोणि व्यायाम जस्तै केगल्स गर्नुस् ताकि महिनावारी स्वास्थ्य सुधार गर्न सकियोस्।",
            "तपाईंको शरीरको लागि सहज महसुस हुने महिनावारी उत्पादन प्रयोग गर्नुहोस्।",
            "महिनावारीको समयमा चिनी कम खानुहोस् ताकि ऊर्जा स्तर स्थिर रहोस्।",
            "तपाईंको सुत्ने समय नियमित राख्नुहोस् ताकि थकान कम गर्न सकियोस्।",
            "प्राकृतिक फेस वाश र सौम्य साबुन प्रयोग गरी सरसफाइ कायम राख्नुहोस्।",
            "महिनावारी हुँदा नियमित रूपमा स्नान गर्नुहोस् ताकि आरामदायी महसुस होस्।",
            "अत्यधिक मसालेदार खाना खपत नगर्नुहोस् ताकि पेटको समस्याबाट बच्न सकियोस्।",
            "साधारण एक्सर्साइज जस्तै स्ट्रेचिङले मांसपेशीलाई आराम दिन मद्दत गर्छ।",
            "महिनावारी चक्रको बारेमा अझ राम्ररी बुझ्नका लागि स्वस्थ्य सामग्री पढ्नुहोस्।",
            "महिनावारीका समयमा ध्यान र शान्तिपूर्ण संगीतले तनाव कम गर्न सहयोग गर्छ।",
            "नरम र हावा पास हुने कपडा लगाउनुहोस् ताकि आराम महसुस होस्।",
            "गर्मीको समयमा महिनावारी हुँदा अत्यधिक पसिना रोक्न हावा-प्रवाह हुने अन्तर्वस्त्र प्रयोग गर्नुहोस्।",
            "भिटामिन-सी युक्त फलफूल जस्तै सुन्तला खानुहोस् ताकि ऊर्जा बढाउन सकियोस्।",
            "तपाईंको स्वास्थ्य स्थिति बुझ्नको लागि वार्षिक स्त्रीरोग विशेषज्ञको जाँच गराउनुहोस्।",
            "महिनावारीको समयमा हल्का, घरमै बनाइएको खाना प्राथमिकता दिनुहोस्।",
            "महिनावारी कप सुरु गर्नुअघि यसको प्रयोग विधिको बारेमा सिक्नुहोस्।",
            "भारी फ्लो भएका दिनहरूमा डबल प्रोटेक्शन प्रयोग गर्नुहोस् (प्याड र ट्याम्पन सँगै)।",
            "पेटमा दुखाइ कम गर्न हल्का मालिस गर्नुहोस्।",
            "धेरै गहिरो महिनावारीको लक्षणहरूलाई बेवास्ता नगर्नुहोस्।",
            "स्यानिटरी उत्पादनहरूको सही डिस्पोजल विधि अपनाउनुहोस्।",
            "साथीहरूसँग महिनावारी सम्बन्धी अनुभवहरू साझेदारी गर्नुहोस्।",
            "तपाईंको महिनावारी चक्रको अवधि अनुमान गर्नका लागि नियमितता ट्र्याक गर्नुहोस्।",
            "पेट फुलावट कम गर्न औषधीय चिया जस्तै पुदीना वा फेनल चिया प्रयोग गर्नुहोस्।",
            "तपाईंको महिनावारीको समयमा उत्पन्न हुने भावनात्मक उतारचढावलाई सम्हाल्न मानसिक स्वास्थ्य व्यायाम गर्नुहोस्।",
            "प्राकृतिक मह र नुनले बनाइएको घरेलु उपचारले दाग हटाउन मद्दत गर्न सक्छ।",
            "महिनावारी हुँदा लामो समय बस्नुभन्दा हल्का हिँडडुल गर्नुहोस्।"
    };



}
